Mainnet and Testnet toggle [PRO-1316]
etherspot/etherspot-react-transaction-buidler pull request #149
Opened 2023-05-18 05:14 UTC by parag-chauhan

## Description
Toggle between mainnet and testnet toggle in settings menu.

## Motivation and Context
Mainnet and testnet toggle helps developers to use the builder in testnet mode.

## How Has This Been Tested?
- Send transaction
https://mumbai.polygonscan.com/tx/0xff37ac463b150b138d096517e8401a014c8bb3c6607460e6144e2702110ce77b

## Screenshots:
![image](https://github.com/etherspot/etherspot-react-transaction-buidler/assets/109526304/0f790e53-cc29-42b3-9361-516612d01984)
![Peek 2023-05-18 10-42](https://github.com/etherspot/etherspot-react-transaction-buidler/assets/109526304/d7f0955e-bfc3-4667-83ee-2ed3671aa52f)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-05-18 10:57 UTC, arddluma requested changes

2023-05-18 10:57 UTC, arddluma commented on src/utils/chain.ts
> +    title: 'Arbitrum Rinkeby',
Please remove this as it is deprecated now @parag-chauhan

2023-05-18 10:57 UTC, arddluma commented on src/utils/chain.ts
> +    title: 'POA Network Sokol',
Sokol is replaced with `Chiado`

2023-05-23 07:00 UTC, MayukhSamadder2000 approved these changes
LGTM

2023-05-24 07:22 UTC, merged