add transaction history on history page
etherspot/etherspot-react-transaction-buidler pull request #194
Opened 2023-08-23 07:09 UTC by bhumitaylor14

## Description
Write function to get transactions data from sdk and then  put returned data array in crosschainaction array same like stored in cache. but some fields are missing in sdk returned data so, put them static to make some progress on this ticket. Scroll is pending , we need to put scroll to display all transactions.
-

## Motivation and Context
https://linear.app/pillarproject/issue/PRO-1192/transaction-history
-

## How Has This Been Tested?
Testing using one account which has transactions inside it. scroll functionality is pending
Testend on my local machine
changes on History page only.

## Screenshots (if appropriate):
<img width="471" alt="Screenshot 2023-08-23 at 12 35 58 PM" src="https://github.com/etherspot/etherspot-react-transaction-buidler/assets/141008551/7bfaae09-eb83-46c2-a662-1b5d0bc5c5cb">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ Tick] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-08-23 12:38 UTC, Yash-Chaubal requested changes
Good work so far, but there's still some work needed

2023-08-23 12:38 UTC, Yash-Chaubal commented on src/components/History/History.tsx
> +import { uniqueId } from 'lodash';
This should be moved above the local imports, under `from 'react'`.

2023-08-23 12:38 UTC, Yash-Chaubal commented on src/components/History/History.tsx
> +      }
Remove the unused else statement

2023-08-23 12:38 UTC, Yash-Chaubal commented on src/components/History/History.tsx
> +        setStoredGroupedCrossChainActions(storedGroupedCrossChainActionsUpdated);
We're checking `storedGroupedCrossChainActionsRaw` twice here - any reason you added an if statement here when there was already a check in place? `storedGroupedCrossChainActionsRaw ? JSON.parse(storedGroupedCrossChainActionsRaw) : {};`

2023-08-23 12:38 UTC, Yash-Chaubal commented on src/components/History/History.tsx
> +      let storedGroupedCrossChainActionsRaw = getItem(STORED_GROUPED_CROSS_CHAIN_ACTIONS);
Variables that aren't changed should remain as `const` instead of `let`

2023-08-23 12:38 UTC, Yash-Chaubal commented on src/components/History/History.tsx
> +  const getTransactionsData = async () => {
Just add a line break above this for readability

2023-08-23 12:38 UTC, Yash-Chaubal commented on src/components/History/History.tsx
> +      let results = await fetchTransactionsData(sdk, accountAddress);
Why are we only getting transactions for Polygon? Shouldn't we be getting history for all chains?

2023-08-23 12:38 UTC, Yash-Chaubal commented on src/components/History/History.tsx
> +          };
I saw your comment about using static values for testing, but I'm just leaving this comment as a reminder to remove the hardcoded values before merging anything to develop

2023-08-23 12:38 UTC, Yash-Chaubal commented on src/utils/transaction.ts
> +  console.log(results);
Remove any console logs

2023-08-24 04:34 UTC, bhumitaylor14 commented
@Yash-Chaubal , I have seen your comments on my code for history , will look into this after completing high priority task and raise PR again

2023-09-29 07:53 UTC, IAmKio commented
@bhumitaylor14 just wondering what this PR is for? It's looking stale now

2023-09-29 07:57 UTC, bhumitaylor14 commented
> @bhumitaylor14 just wondering what this PR is for? It's looking stale now

@IAmKio, now no need for this PR , I have raised PR when I started working without design and after that we created new ticket and defined new approach so, now no need to merge this PR

2023-09-29 07:57 UTC, IAmKio commented
thanks for the update @bhumitaylor14 please close the ticket

2023-10-03 06:47 UTC, closed without merging